# Generated by Django 3.0.3 on 2020-05-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('others', models.IntegerField()),
                ('Totalsalary', models.IntegerField()),
            ],
        ),
    ]
