# Generated by Django 3.0.3 on 2020-05-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='first_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
