# Generated by Django 3.0.3 on 2020-05-21 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0002_contactform_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='Totalsalary',
        ),
    ]
