# Generated by Django 3.0.3 on 2020-05-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0004_remove_contactform_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='first_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
