# Generated by Django 3.0.3 on 2020-05-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0005_contactform_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userexpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('travelling', models.IntegerField()),
                ('others', models.IntegerField()),
                ('expense', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Userincome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Totalsalary', models.IntegerField()),
            ],
        ),
    ]
