# Generated by Django 3.0.3 on 2020-05-24 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0006_userexpense_userincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=250)),
                ('amount', models.FloatField()),
                ('addedon', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=250)),
                ('amount', models.FloatField()),
                ('addedon', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=64)),
                ('Email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.DeleteModel(
            name='Userexpense',
        ),
        migrations.DeleteModel(
            name='Userincome',
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgmt.User'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgmt.User'),
        ),
    ]
